[package]
name = "raytracer"
version = "0.1.0"
authors = ["FractalArt"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7"
image = "0.22.0"
